name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

#    - name: call-reusable
#      uses: org/reusable-workflows/.github/workflows/deploy.yml@v1
#      with:
#        python_version: '3.11'
#      secrets:
#        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
