name: Deploy using Reusable Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  call-reusable:
    uses: dariasmoises979-blip/pipeline-build/.github/workflows/docker-publish.yml@main
    with:
      python_version: '3.11'
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}