name: workflow-dev

on:
  pull_request:
    branches:
      - main  # rama de destino del PR

jobs:
  example-job:
    uses: dariasmoises979-blip/pipeline-build/.github/workflows/docker-publish.yml@main


