name: workflow-dev

on:
  pull_request:
    branches:
      - main  # rama de destino del PR

jobs:
  example-job:
    uses: dariasmoises979-blip/pipeline-build/.github/workflows/docker-publish.yml@main


    with:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      image_name: 'dariasmoises979/blip-app'
      image_tag: 'pr-${{ github.event.number }}'