name: My App CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: dariasmoises979-blip/pipeline-build/.github/workflows/docker-publish.yml@main # Aquí el 'main' es la rama del shared-workflows
    with:
      image-name: moises
      dockerfile-path: ./Dockerfile
      registry-username: moises # El username ya no es secreto
    secrets:
      # Solo el token es secreto
      REGISTRY_TOKEN: ${{ secrets.GH_TOKEN }}



 