name: Build & Publish using Reusable Workflow

on:
  pull_request:
    branches:
      - main  # rama de destino del PR

jobs:
  call-reusable:
    uses: dariasmoises979-blip/pipeline-build/.github/workflows/docker-publish.yml@main
    with:
      docker_image: flask-info-app
      dockerhub_username: dariasmoises979  
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

