name: Call Reusable Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  call-hello-world:
    uses: dariasmoises979-blip/pipeline-build/.github/workflows/docker-publish.yml@main # Aquí el 'main' es la rama del shared-workflows


    secrets:
      # Solo el token es secreto
      REGISTRY_TOKEN: ${{ secrets.GH_TOKEN}}

 