name: Notificar a Slack

on:
  push:
    branches:
      - main  # Cambia esta rama si es necesario

jobs:
  notificar:
    runs-on: ubuntu-latest

    steps:
      - name: Enviar mensaje a Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data "{
            \"text\": \":rocket: Nuevo push en *${{ github.repository }}* por *${{ github.actor }}* en la rama *${{ github.ref_name }}*.\n
            Commit: <${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|Ver commit>\"
          }" \
          $SLACK_WEBHOOK_URL
          
