name: Notificar a Slack

on:
  push:
    branches:
      - main  # Cambia si usas otra rama

jobs:
  notificar:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar mensaje a Slack
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data "{\"text\":\"🚀 Nuevo push en *${{ github.repository }}* por *${{ github.actor }}* en la rama *${{ github.ref_name }}*.\"}" \
          $SLACK_WEBHOOK_URL
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
